export const data = [
  {
    id: 1,
    account_name: 'Jhop Beer',
    account_id: 'AB-123',
    annual_revenue: '$1 - $10M',
    score: 'High',
    due_date: '26 Jan 2023',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
  {
    id: 2,
    account_name: 'Soylent corp',
    account_id: '--',
    annual_revenue: '$1 - $10M',
    score: 'Medium',
    due_date: '03 Jan 2023',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
  {
    id: 3,
    account_name: 'Wakanda industries',
    account_id: 'AB-123',
    annual_revenue: '$1 - $10M',
    score: 'Low',
    due_date: '05 Feb 2023',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
  {
    id: 4,
    account_name: 'Wayne Interpeises',
    account_id: 'AB-123',
    annual_revenue: '$1 - $10M',
    score: '',
    due_date: '--',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
  {
    id: 5,
    account_name: 'Nami',
    account_id: '--',
    annual_revenue: '$1 - $2M',
    score: '',
    due_date: '26 Jan 2023',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
  {
    id: 6,
    account_name: 'Bruce wayne',
    account_id: 'AB-123',
    annual_revenue: '$1 - $10M',
    score: 'High',
    due_date: '26 Jan 2023',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
  {
    id: 7,
    account_name: 'Tony Stark',
    account_id: 'AB-123',
    annual_revenue: '$1 - $10M',
    score: 'High',
    due_date: '26 Jan 2023',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
  {
    id: 8,
    account_name: 'Demon Slayer',
    account_id: 'AB-123',
    annual_revenue: '$1 - $10M',
    score: 'High',
    due_date: '26 Jan 2023',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
  {
    id: 9,
    account_name: 'Zoro',
    account_id: 'AB-123',
    annual_revenue: '$1 - $10M',
    score: 'High',
    due_date: '26 Jan 2023',
    assignee: [],
    priority: 'high',
    tag: 'recurring',
  },
];

export const columns = [
  {
    Header: '#',
    accessor: 'id',
    // sortType: (a, b) => {
    //   const numA = parseInt(a, 10);
    //   const numB = parseInt(b, 10);
    //   return numA - numB;
    // },
  },
  {
    Header: 'Account Name',
    accessor: 'account_name',
  },
  {
    Header: 'Account ID',
    accessor: 'account_id',
  },
  {
    Header: 'Annual Revenue',
    accessor: 'annual_revenue',
  },
  {
    Header: 'Score',
    accessor: 'score',
  },
  {
    Header: 'Due Date',
    accessor: 'due_date',
  },
  {
    Header: 'Assignee',
    accessor: 'assignee',
  },
  {
    Header: 'Priority',
    accessor: 'priority',
  },
  {
    Header: 'Tag',
    accessor: 'tag',
  },
];
