name: Build Electron App

on:
  push:
    branches:
      - develop  # Replace with your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up macOS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          platform: 'darwin'
          
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm -r install
        
      - name: Build Electron app for macOS
        run: pnpm run package

      - name: Archive macOS artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-app-mac
          path: release/build/mac
